-- Seed ~91 additional musicals to bring the catalog to 100.
-- The 9 already in the database are excluded:
--   chicago, dear-evan-hansen, hadestown, hamilton, les-mis, rent, lion-king, phantom, wicked

INSERT INTO musicals (id, title, year, description) VALUES
-- Golden Age (1940s–1960s)
('oklahoma', 'Oklahoma!', 1943, 'A high-spirited cowboy and a stubborn farm girl navigate love and rivalry in Indian Territory at the dawn of statehood.'),
('carousel', 'Carousel', 1945, 'A smooth-talking carnival barker falls for a millworker, but his reckless choices follow them beyond the grave.'),
('annie-get-your-gun', 'Annie Get Your Gun', 1946, 'Sharpshooter Annie Oakley joins Buffalo Bill''s Wild West show and discovers that winning isn''t everything when love is on the line.'),
('south-pacific', 'South Pacific', 1949, 'On a tropical island during World War II, two unlikely romances challenge deep-seated prejudice and fear.'),
('guys-and-dolls', 'Guys and Dolls', 1950, 'A charming gambler bets he can woo a prim Salvation Army sergeant while his pal stalls on marrying his longtime fiancee.'),
('king-and-i', 'The King and I', 1951, 'A British governess clashes with the stubborn King of Siam as she teaches his children and slowly changes his heart.'),
('my-fair-lady', 'My Fair Lady', 1956, 'A brash Cockney flower seller is transformed into a society lady by a phonetics professor who may have met his match.'),
('west-side-story', 'West Side Story', 1957, 'Two young lovers are caught between rival street gangs on Manhattan''s West Side in a modern retelling of Romeo and Juliet.'),
('gypsy', 'Gypsy', 1959, 'The ultimate stage mother pushes her daughters toward stardom, but it''s the overlooked one who becomes a burlesque legend.'),
('sound-of-music', 'The Sound of Music', 1959, 'A spirited young nun becomes governess to seven children and helps their widowed father rediscover joy as war closes in.'),
('bye-bye-birdie', 'Bye Bye Birdie', 1960, 'A rock star''s draft notice sends a small Ohio town into a frenzy when he''s scheduled to give one last kiss to a lucky fan.'),
('how-to-succeed', 'How to Succeed in Business Without Really Trying', 1961, 'An ambitious window-washer climbs the corporate ladder using a self-help book and an irresistible grin.'),
('funny-girl', 'Funny Girl', 1964, 'Fanny Brice rises from the streets of New York to become a Ziegfeld star, but her heart belongs to a charming gambler.'),
('fiddler-on-the-roof', 'Fiddler on the Roof', 1964, 'A Jewish milkman in a small Russian village tries to hold onto tradition as the modern world reshapes his daughters'' lives.'),
('hello-dolly', 'Hello, Dolly!', 1964, 'A matchmaker meddles in everyone else''s love life while secretly setting the perfect trap for a wealthy merchant.'),
('man-of-la-mancha', 'Man of La Mancha', 1965, 'Cervantes defends his unfinished manuscript before the Spanish Inquisition by performing the tale of the idealistic Don Quixote.'),
('cabaret', 'Cabaret', 1966, 'Inside a seedy Berlin nightclub, a young American writer and a free-spirited singer ignore the rising tide of Nazism — until they can''t.'),
('oliver', 'Oliver!', 1963, 'A workhouse orphan escapes to the streets of Victorian London and falls in with a lovable gang of pickpockets.'),

-- 1970s
('godspell', 'Godspell', 1971, 'A ragtag community acts out parables and teachings of Jesus through clowning, vaudeville, and infectious song.'),
('jesus-christ-superstar', 'Jesus Christ Superstar', 1971, 'The final days of Jesus are retold through a rock opera lens, seen largely through the eyes of Judas Iscariot.'),
('grease', 'Grease', 1972, 'A summer romance between a tough greaser and a sweet transfer student is tested by peer pressure at Rydell High.'),
('pippin', 'Pippin', 1972, 'A young prince searches for meaning through war, politics, and love, guided — and manipulated — by a mysterious troupe of performers.'),
('little-night-music', 'A Little Night Music', 1973, 'A weekend in the Swedish countryside tangles the love lives of several couples in a waltz of jealousy and regret.'),
('chorus-line', 'A Chorus Line', 1975, 'Seventeen dancers bare their souls in a grueling Broadway audition, each hoping for a spot on the line.'),
('annie', 'Annie', 1977, 'A plucky orphan wins the heart of a billionaire and charms Depression-era New York while searching for her real parents.'),
('sweeney-todd', 'Sweeney Todd: The Demon Barber of Fleet Street', 1979, 'A vengeful barber returns to Victorian London with a razor and a dark partnership that serves up justice in the most gruesome way.'),
('evita', 'Evita', 1979, 'Eva Peron rises from poverty to become Argentina''s most powerful and controversial First Lady in this sweeping rock opera.'),

-- 1980s
('42nd-street', '42nd Street', 1980, 'A small-town girl gets her big break when the leading lady of a Broadway show breaks her ankle on opening night.'),
('dreamgirls', 'Dreamgirls', 1981, 'A Motown-inspired girl group rockets to fame, but success threatens to tear apart the friendships that started it all.'),
('cats', 'Cats', 1982, 'A tribe of cats gathers for an annual ball where one will be chosen to ascend to a new life, each making their case in song.'),
('la-cage-aux-folles', 'La Cage aux Folles', 1983, 'A flamboyant nightclub owner and his drag-queen partner try to play it straight when their son brings home his fiancee''s conservative parents.'),
('sunday-in-the-park', 'Sunday in the Park with George', 1984, 'Pointillist painter Georges Seurat sacrifices human connection for art, and a century later his great-grandson faces the same struggle.'),
('big-river', 'Big River', 1985, 'Huck Finn and the runaway slave Jim raft down the Mississippi in a country-folk retelling of Mark Twain''s classic.'),
('me-and-my-girl', 'Me and My Girl', 1986, 'A Cockney bloke inherits an earldom and must learn upper-class manners — without losing the girl he loves.'),
('into-the-woods', 'Into the Woods', 1987, 'Fairy-tale characters discover that getting your wish is only the beginning when their stories collide in the woods.'),
('miss-saigon', 'Miss Saigon', 1991, 'A doomed love story between a Vietnamese woman and an American soldier unfolds during the fall of Saigon.'),

-- 1990s
('crazy-for-you', 'Crazy for You', 1992, 'A stage-struck New Yorker is sent to foreclose on a theater in Deadrock, Nevada, and decides to save it with a show instead.'),
('kiss-of-the-spider-woman', 'Kiss of the Spider Woman', 1993, 'Two prisoners in a Latin American jail — a political radical and a romantic dreamer — forge an unlikely bond through fantasy and film.'),
('beauty-and-the-beast', 'Beauty and the Beast', 1994, 'A bookish young woman becomes the prisoner of a cursed prince and discovers there''s more to him than meets the eye.'),
('smokey-joes-cafe', 'Smokey Joe''s Cafe', 1995, 'The songs of Leiber and Stoller come alive in a high-energy revue spanning rock, pop, and rhythm and blues.'),
('victor-victoria', 'Victor/Victoria', 1995, 'A struggling soprano pretends to be a man pretending to be a woman in 1930s Paris — and fools everyone except the one who matters.'),
('bring-in-da-noise', 'Bring in ''da Noise, Bring in ''da Funk', 1996, 'The African-American experience is told through the explosive rhythms of tap dance, from slavery to the modern city.'),
('titanic', 'Titanic', 1997, 'Passengers from every class board the unsinkable ship, each carrying dreams that collide with fate on that fateful night.'),
('ragtime', 'Ragtime', 1998, 'Three families — Black, white, and immigrant — collide in early 1900s New York in a sweeping portrait of the American dream.'),
('footloose', 'Footloose', 1998, 'A city kid moves to a small town where dancing is banned and rallies the local teens to fight for their right to cut loose.'),
('parade', 'Parade', 1998, 'The true story of Leo Frank, a Jewish factory manager wrongly convicted of murder in 1913 Atlanta, and the fight for justice.'),
('aida', 'Aida', 2000, 'A Nubian princess captured by the Egyptians falls in love with a military captain, testing loyalty, duty, and love.'),

-- 2000s
('producers', 'The Producers', 2001, 'Two scheming Broadway producers discover they can make more money with a flop — until their terrible show becomes a hit.'),
('mamma-mia', 'Mamma Mia!', 2001, 'A bride-to-be on a Greek island invites three men from her mother''s past, hoping to discover which one is her father.'),
('urinetown', 'Urinetown', 2001, 'In a future where a toilet monopoly charges citizens to pee, a young rebel leads a revolution — in this gleefully absurd satire.'),
('thoroughly-modern-millie', 'Thoroughly Modern Millie', 2002, 'A small-town girl arrives in 1920s New York determined to marry for money, but love has other plans.'),
('hairspray', 'Hairspray', 2002, 'A plus-size teenager dances her way onto a Baltimore TV show in the 1960s and fights to integrate the program.'),
('movin-out', 'Movin'' Out', 2002, 'Five friends from Long Island navigate love, war, and disillusionment across the decades, set to the music of Billy Joel.'),
('avenue-q', 'Avenue Q', 2003, 'A fresh-out-of-college puppet and his neighbors learn that life after school is messy, awkward, and hilariously real.'),
('spamalot', 'Spamalot', 2005, 'King Arthur and his Knights of the Round Table embark on a quest for the Holy Grail in this irreverent Monty Python adaptation.'),
('color-purple', 'The Color Purple', 2005, 'Celie''s journey from abuse to self-discovery in the early 1900s Deep South becomes a soaring testament to resilience and love.'),
('jersey-boys', 'Jersey Boys', 2005, 'Four guys from Newark become Frankie Valli and the Four Seasons, but fame tests every bond that got them there.'),
('25th-annual-putnam', 'The 25th Annual Putnam County Spelling Bee', 2005, 'Six quirky kids compete in a spelling bee, each revealing the pressures and dreams that drive them to win.'),
('spring-awakening', 'Spring Awakening', 2006, 'Repressed teenagers in 1890s Germany discover desire, identity, and rebellion through raw rock anthems.'),
('curtains', 'Curtains', 2007, 'When the star of a new musical is murdered on opening night, a detective who loves theater must find the killer before the show closes.'),
('in-the-heights', 'In the Heights', 2008, 'A tight-knit Latino community in Washington Heights chases dreams of a better life over the course of three sweltering summer days.'),
('next-to-normal', 'Next to Normal', 2009, 'A suburban mother battles bipolar disorder while her family struggles to hold together around the cracks in their picture-perfect life.'),
('billy-elliot', 'Billy Elliot', 2008, 'An 11-year-old miner''s son in northern England discovers a passion for ballet that defies his father''s expectations and his community''s norms.'),
('memphis', 'Memphis', 2009, 'A white radio DJ and a Black club singer defy 1950s Memphis to bring rock and roll to the airwaves and change music forever.'),

-- 2010s
('book-of-mormon', 'The Book of Mormon', 2011, 'Two mismatched Mormon missionaries are sent to Uganda, where their faith is hilariously and profoundly tested.'),
('newsies', 'Newsies', 2012, 'Scrappy newspaper boys in 1899 New York rally together to strike against publishing tycoon Joseph Pulitzer.'),
('once', 'Once', 2012, 'A Dublin street musician and a Czech immigrant connect through music over the course of a few transformative days.'),
('kinky-boots', 'Kinky Boots', 2013, 'A struggling shoe factory finds salvation by teaming up with a fabulous drag queen to produce a line of glamorous boots.'),
('matilda', 'Matilda the Musical', 2013, 'A gifted little girl with a vivid imagination stands up to the tyrannical adults in her life armed with books and bravery.'),
('gentleman-guide', 'A Gentleman''s Guide to Love & Murder', 2013, 'A distant heir cheerfully eliminates the eight relatives standing between him and a family fortune in this gleeful Edwardian romp.'),
('aladdin', 'Aladdin', 2014, 'A charming street urchin discovers a magic lamp and a genie who grants him three wishes — but winning the princess takes more than magic.'),
('fun-home', 'Fun Home', 2015, 'A young cartoonist pieces together her childhood, her closeted father''s secret life, and her own coming-out in this intimate memoir musical.'),
('school-of-rock', 'School of Rock', 2015, 'A wannabe rock star poses as a substitute teacher and turns his class of straight-A students into the ultimate garage band.'),
('waitress', 'Waitress', 2016, 'A small-town waitress pours her troubles into extraordinary pies while dreaming of a way out of her unhappy marriage.'),
('great-comet', 'Natasha, Pierre & The Great Comet of 1812', 2016, 'A young countess falls for a rakish scoundrel in Moscow while her fiance is away at war, in this electropop retelling of Tolstoy.'),
('come-from-away', 'Come from Away', 2017, 'When 38 planes are diverted to a tiny Newfoundland town on 9/11, the locals open their hearts to 7,000 stranded strangers.'),
('mean-girls', 'Mean Girls', 2018, 'A homeschooled teenager navigates the cutthroat social hierarchy of a suburban high school and its reigning clique of popular girls.'),
('the-prom', 'The Prom', 2018, 'Broadway narcissists descend on a small Indiana town to help a lesbian teen banned from bringing her girlfriend to prom.'),
('beetlejuice', 'Beetlejuice', 2019, 'A recently deceased couple and a mischievous demon team up to scare away the insufferable new owners of their home.'),
('moulin-rouge', 'Moulin Rouge! The Musical', 2019, 'A penniless songwriter falls for a dazzling star at the legendary Parisian nightclub, where love battles jealousy and ambition.'),
('tina', 'Tina: The Tina Turner Musical', 2019, 'Tina Turner overcomes an abusive marriage and the music industry''s doubts to become the unstoppable Queen of Rock ''n'' Roll.'),
('jagged-little-pill', 'Jagged Little Pill', 2019, 'A seemingly perfect Connecticut family unravels when hidden pain surfaces, scored by the raw anthems of Alanis Morissette.'),
('six', 'Six', 2021, 'The six wives of Henry VIII take the mic and remix their stories into a fierce pop concert to crown the queen who had it worst.'),
('company', 'Company (2021 Revival)', 2021, 'A single woman on her 35th birthday examines love, marriage, and friendship through the lens of her coupled-up friends.'),
('some-like-it-hot', 'Some Like It Hot', 2022, 'Two musicians on the run from the mob disguise themselves as women and join an all-female band in this Jazz Age romp.'),
('merrily-we-roll-along', 'Merrily We Roll Along', 2023, 'The story of a friendship between a composer, a writer, and an actress unfolds in reverse, from bitter estrangement back to youthful hope.'),
('outsiders', 'The Outsiders', 2024, 'Greasers and Socs collide in 1960s Tulsa as a teenager learns that loyalty, loss, and growing up don''t follow simple lines.'),
('suffs', 'Suffs', 2024, 'The young radicals of the women''s suffrage movement clash with their elders and the government in the fight for the 19th Amendment.'),
('great-gatsby', 'The Great Gatsby', 2024, 'Jay Gatsby throws lavish parties on Long Island, all in pursuit of a lost love, in this jazz-drenched adaptation of Fitzgerald''s novel.'),
('little-shop', 'Little Shop of Horrors', 1982, 'A meek flower-shop assistant discovers that his mysterious new plant craves human blood — and grants wishes in return.'),
('little-mermaid', 'The Little Mermaid', 2008, 'A young mermaid princess makes a dangerous deal with a sea witch to trade her voice for legs and a chance at true love.');
